### ISSUE TITLE
open automation test quiz of Breezy

### ISSUE THREAD

**Issue by Breezy571** [nnnlyy/open_automation_test_quiz#1]
1.  git repository: https://github.com/Breezy571/open_automation_quiz.git
2. chrome 131.0.6778.87  edge:131.0.2903.70
3. source code path: ./python
4. screenshots path: ./python/topic_cucumber/screenshots
5. report path: ./python/topic_cucumber/report.html

**Comment by nnnlyy** [comment]
Received your project, I'll feedback soon.

Thank you.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Breezy571 ***@***.***>
Sent: Sunday, December 8, 2024 10:00:27 AM
To: nnnlyy/open_automation_test_quiz ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nnnlyy/open_automation_test_quiz] open automation test quiz of Breezy (Issue #1)


  1.  git repository: https://github.com/Breezy571/open_automation_quiz.git
  2.  chrome 131.0.6778.87 edge:131.0.2903.70
  3.  source code path: ./python
  4.  screenshots path: ./python/topic_cucumber/screenshots
  5.  report path: ./python/topic_cucumber/report.html

―

**Comment by nnnlyy** [comment]
> 1. git repository: https://github.com/Breezy571/open_automation_quiz.git
> 2. chrome 131.0.6778.87  edge:131.0.2903.70
> 3. source code path: ./python
> 4. screenshots path: ./python/topic_cucumber/screenshots
> 5. report path: ./python/topic_cucumber/report.html

Hi Breezy,
could you please tell me your real name? 
thanks~
