### ISSUE TITLE
项目链接

### ISSUE THREAD

**Issue by liurx4** [nnnlyy/open_automation_test_quiz#4]
https://github.com/liurx4/open_automation_test_quiz
工程里面有答题的说明文档，请查阅，感谢。

**Comment by nnnlyy** [comment]
@liurx4 
Received, I'll feedback soon, 
Thanks for your hard working.

**Comment by nnnlyy** [comment]
@liurx4 
Could you please tell me your real name?

**Comment by liurx4** [comment]
my name is 刘荣心.

**Comment by nnnlyy** [comment]
Got it，thanks.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
